### ISSUE TITLE
Add sample for creating a conversation

### ISSUE THREAD

**Issue by TrucHLe** [googleapis/nodejs-contact-center-insights#27]
I'd like to add a sample for https://cloud.google.com/contact-center/insights/docs/create-analyze-conversation-api. This sample will create a conversation. The unit test of this sample will create a conversation and delete the created resource.

**Comment by bcoe** [comment]
@TrucHLe here's a link to [sample policies](https://g3doc.corp.google.com/company/teams/cloud-devrel/dpe/samples/nodejs.md?cl=head) which you can use to get started 👍 

Here are some good examples of samples with tests to work from:

https://github.com/googleapis/nodejs-secret-manager/blob/master/samples/enableSecretVersion.js
